version: '3.1'

services:
    flowise:
        image: flowiseai/flowise:${SOFTWARE_VERSION_TAG}
        restart: always
        environment:
            - PORT=3965
        ports:
            - '172.17.0.1:3965:3000'
        volumes:
            - ./.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"